/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication12;

import java.awt.Color;
import javax.swing.JProgressBar;

/**
 *
 * @author hp
 */
public class progressframe2 extends javax.swing.JFrame {
         pbThread t1;
    /**
     * Creates new form progressframe2
     */
    public progressframe2() {
        initComponents();
//        Pgbar.setForeground(Color.red);
         t1=new pbThread(Pgbar);
        t1.start();
    }
    
    
   public static class pbThread extends Thread {
    
JProgressBar pbar;
pbThread(JProgressBar pbar){
    pbar=Pgbar;
}
   public void run(){
       
   int min=0;
   int max=100;
   Pgbar.setMaximum(min);
    Pgbar.setMaximum(max);
     Pgbar.setValue(0);
        for(int i=min;i<max;i++){
             Pgbar.setValue(i);
             pertxt.setText(Integer.toString(i)+"%");
       try {
           sleep(50);
       } catch (InterruptedException ex) {
          System.out.println("Error");
       }
    }
}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pertxt = new javax.swing.JLabel();
        Pgbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pertxt.setText("100%");
        getContentPane().add(pertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, -1, -1));

        Pgbar.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(Pgbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 680, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 300, 290));

        jLabel2.setText(" ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progressframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progressframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progressframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progressframe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progressframe2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar Pgbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel pertxt;
    // End of variables declaration//GEN-END:variables
}
