/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.activation.MailcapCommandMap;
import javax.activation.URLDataSource;
import javax.activation.MimeType;
import javax.activation.MimeTypeParameterList;
import javax.activation.MimetypesFileTypeMap;


/**
 *
 * @author AmanTomar
 */
public class welcom extends javax.swing.JFrame {

    /**
     * Creates new form welcom
     */
    public welcom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("WELCOME");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
//         String to = "sachinsingh123098@gmail.com";
//     String from = "sachinrrrrock0890@gmail.com";
//     String pass ="sachinsingh";
//     String subj = "Your complain is register succesfully";
//      String msg = "hello bro what we will do in ca  ";
//     
//    
//     
//         Properties properties = new Properties();
//         properties.put("mail.smtp.auth", "true");
//          properties.put("mail.smtp.starttls.enable", "true");
//          properties.setProperty("mail.smtp.socketFactory.port", "465");
//           properties.put("mail.smtp.host", "smtp.gmail.com");
//          //  properties.put("mail.smtp.port", "587");
//            properties.put("mail.smtp.starttls.enable","true");
//            
//            
//          // properties.put("mail.smtp.host", "10.101.3.229");
//     
//            Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
//            @Override
//            protected PasswordAuthentication getPasswordAuthentication(){
//                return new PasswordAuthentication(from,pass);
//            }
//            });
//            
//            
//            MimeMessage message = new MimeMessage(session);
//            
//            try {
//                message.setFrom(new InternetAddress (from));
//            } catch (MessagingException ex) {
//                System.out.println("error in from");
//            }
//            try {
//                message.addRecipient (Message.RecipientType.TO, new InternetAddress (to) ) ;
//            } catch (MessagingException ex) {
//               System.out.println("error in to ");
//            }
//            try {
//                message. setSubject (subj) ;
//            } catch (MessagingException ex) {
//                System.out.println("error in subj");
//            }
//            try {
//                message. setText (msg ) ;
//            } catch (MessagingException ex) {
//                System.out.println("error in msg");
//            }
//    
//            
//        try {
//            Transport.send(message);
//        } catch (MessagingException ex) {
//            Logger.getLogger(email.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            ///////////////////////////////////////////////////////////////////////////////////////
            
            
          
SendMail sendMail = new SendMail();

sendMail.send("abinashkumarsharma21@gmail.com", "sachinrrrrock0890@gmail.com", "kya tu h? ", "isme koi Shak ni vo to he hi ......");


            
            
         ////////////////////////////////////////////////////////////////////////////////////////////
//Properties props = new Properties();
//props.put("mail.smtp.auth", "true");
//props.put("mail.smtp.starttls.enable", "true");
//props.put("mail.smtp.host", "smtp.gmail.com");
//props.put("mail.smtp.port", "587");
//
//Session session = Session.getInstance(props, new javax.mail.Authenticator() {
//    protected PasswordAuthentication getPasswordAuthentication() {
//        return new PasswordAuthentication("sachinrrrock0890@gmail.com", "sachinsingh");
//    }
//});
//
//try {
//    Message message = new MimeMessage(session);
//    message.setFrom(new InternetAddress("sachinrrrock0890@gmail.com"));
//    message.setRecipients(Message.RecipientType.TO, InternetAddress.parse("sachinsingh123098@gmail.com"));
//    message.setSubject("Testing STARTTLS email");
//    message.setText("Hello, this is a test email!");
//
//    Transport transport = session.getTransport("smtp");
//    transport.connect();
//    transport.sendMessage(message, message.getAllRecipients());
//    transport.close();
//
//    System.out.println("Email sent successfully!");
//} catch (MessagingException e) {
//    throw new RuntimeException(e);
//}


            
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
